### PR TITLE
Support custom development & stable branches

### PR DESCRIPTION
**Pull request by matiasgarciaisaia**
Supersedes #9

### CODE REVIEW

**Review by anaPerezGhiglia — APPROVED** [review]
wonderful! 🙌

**Comment by ysbaddaden** [comment]
I notice that `master` is no longer considered identical to `main`. To upgrade, we must either rename `master` to `main` or set `DEVELOPMENT_BRANCH=master`, right?

**Comment by anaPerezGhiglia** [comment]
@ysbaddaden exactly, `DEVELOPMENT_BRANCH=master` should do the trick just fine 🙂

**Comment by anaPerezGhiglia** [comment]
☝️ notice that the env variable name says `DEV`, not `DEVELOPMENT`

**Pull request merged**
