### PR TITLE
Add support for develop branch build

### PR DESCRIPTION
**Pull request by anaPerezGhiglia**
To give support to the [gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) as well

evidence: https://github.com/manastech/biomakers/runs/1056910083

I put it side-by-side with the `master` behavior, but now I'm wondering if it is ok to have a tag `latest` published by a `develop` branch 🤔 I don't have a strong opinion about this..

### CODE REVIEW

**Comment by anaPerezGhiglia** [comment]
CC: @matiasgarciaisaia @waj

**Comment by matiasgarciaisaia** [comment]
Nice one!

Let's add some tests, for completeness sake :)

And then - I'm 100% for supporting real-world use cases, even if I don't have a strong opinion on what's the best way to support it in this particular scenario.

Not sure if just giving `develop` and `master`the same treatment, or if we should have a "gitflow flag" that makes `master` behave differently when that's on.

@waj?

**Comment by anaPerezGhiglia** [comment]
@matiasgarciaisaia ready the tests for the current implementation 🧪 

what you suggest in your previous comment about a flag for making `master` behave differently makes sense, since in gitflow `master` _means_ something different 🤔

**Comment by matiasgarciaisaia** [comment]
I was thinking that:

1) Yes, please let's implement this change, since it is really needed;

and

2) We should probably have a way to define via an environment variable which branches to consider for the `master/main` case, and provide some sane defaults.

**Comment by matiasgarciaisaia** [comment]
We've _finally_ implemented this in #15 - thanks @anaPerezGhiglia for hanging up to it!

**Pull request closed without merging**
