### PR TITLE
GitHub Action + tag suffix + build options

### LINKED ISSUE #7: Provide a Github Action
Instead of having users fetch the script and run it, we may build a Github Action used with `uses:` to simplify integration.

### PR DESCRIPTION
**Pull request by ysbaddaden**
Fixes #7 by adding the necessary `action.yml` metadata to run build script directly, and the necessary `action.sh` shell script to transform the action inputs into environment variables, .

Also provides two new options, one to pass a tag suffix, for example `-next` to have image tags such as `:1.2.3-next` or `:dev-next`, and another one to pass options to the docker build command, for example `--build gemfile=Gemfile.next`. Those options allows to build 2 variants of CDx for example, the current one with Rails 4.2 _and_ the next one with Rails 5.0.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Sigh, the composite action doesn't work: it runs the `action.sh` from the app, not the one provided by the action :disappointed:

**Comment by ysbaddaden** [comment]
It's _finally_ working. You can see a test run here for example:
https://github.com/instedd/cdx/runs/5773491195?check_suite_focus=true

Is it worth spending more time writing GitHub Actions? No. A single repository with a bunch of Bash or Ruby scripts would be much better.

**Comment by ysbaddaden** [comment]
ping @matiasgarciaisaia

**Comment by matiasgarciaisaia** [comment]
Do you mind adding some tests for the new flags? I can give them a try, otherwise.

**Comment by matiasgarciaisaia** [comment]
Sorry @ysbaddaden - I've deleted the `master` branch (to rename it to `main`) and the PR got auto-closed.

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia I used the opportunity to rebase from `main` and add the missing tests for the `-t` and `-o` arguments in #16!

**Pull request closed without merging**
